### PR TITLE
publish packages to NuGet - closes #1

### LINKED ISSUE #1: Publish to NuGet
Thank you for working on this and releasing this on GitHub as an Open Source library.

Can you please publish this into NuGet?

### PR DESCRIPTION
**Pull request by floydpink**
@pengowray - I have added [a GitHub action](https://github.com/floydpink/TimeSpanParser/runs/520670372?check_suite_focus=true) on my fork which is successfully publishing [this library as a package](https://www.nuget.org/packages/TimeSpanParserUtil/) to NuGet.

[The GitHub action](https://github.com/marketplace/actions/publish-nuget) that I have used builds, tags, pushes the tag to GitHub and publishes a new version to NuGet all by detecting a bump on the `<Version>1.1.0</Version>` element within the `*.csproj`

Before you approve this PR - you'd need to add a new secret [here](https://github.com/pengowray/TimeSpanParser/settings/secrets) named **NUGET_KEY** that is an API Key generated from [your NuGet account](https://www.nuget.org/account/apikeys)

If you want to keep using the same package, I can add you as an owner (and you can keep me there or remove me). :)

### CODE REVIEW

**Comment by floydpink** [comment]
@pengowray - could you kindly look into this, when you get a chance?

**Comment by floydpink** [comment]
Thank you, @pengowray !

Can you please share your nuget.org username? I will add you as an owner of the package.

**Comment by pengowray** [comment]
Hi @floydpink,

Thanks very much for doing this and providing instructions. Sorry I didn't get a chance to look into it sooner.

I've added the nuget key to secrets. If you need it, my nuget username is **qubei** (it used my old Github username)

**Comment by floydpink** [comment]
No worries at all. I have added you as an owner of the NuGet package. 

Once all the tests are passing locally, it’d be good to run the tests from the GitHub Actions as well (as you’d have seen, I’m not running them now).

And once again, thank you for your work on this project and open sourcing it! 😊

**Comment by pengowray** [comment]
Cheers! Thanks for finally dragging this package into nuget. Something I'd been meaning to work out how to do for a long time.

**Pull request merged**
